### ISSUE TITLE
Issue: User Story

### ISSUE THREAD

**Issue by FelipeSeiberlich** [FelipeSeiberlich/6_DAY-PLAN#2]
As a **project manager** I can **check all tasks** so that **project will be delivered on time**.

# TASKS

- [ ] Create a project
- [ ] Enter User Stories
- [ ] Install requirements
- [ ] Set up project
- [ ] Set up app
- [ ] Install app
- [ ] Create a Heroku app
- [ ] Create a database
- [ ] Create a env.py file
- [ ] Modify settings.py
- [ ] Heroku config vars
- [ ] Deployment
